-- ============================================
-- ADMIN DASHBOARD TABLES
-- Beautiful schema for Medicine, Lab Test, and Bed Management
-- ============================================

-- Drop existing tables if you want to recreate them
-- DROP TABLE medicines CASCADE CONSTRAINTS;
-- DROP TABLE lab_tests CASCADE CONSTRAINTS;
-- DROP TABLE hospital_beds CASCADE CONSTRAINTS;

-- ============================================
-- MEDICINES TABLE
-- ============================================
CREATE TABLE medicines (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    description VARCHAR2(500),
    manufacturer VARCHAR2(200),
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    expiry_date DATE,
    category VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_medicine_price CHECK (price >= 0),
    CONSTRAINT chk_medicine_stock CHECK (stock_quantity >= 0)
);

-- Create index for faster searches
CREATE INDEX idx_medicines_name ON medicines(name);
CREATE INDEX idx_medicines_category ON medicines(category);

-- ============================================
-- LAB TESTS TABLE
-- ============================================
CREATE TABLE lab_tests (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    test_name VARCHAR2(200) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10,2) NOT NULL,
    department VARCHAR2(100),
    preparation_required VARCHAR2(500),
    duration_minutes NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_labtest_price CHECK (price >= 0),
    CONSTRAINT chk_labtest_duration CHECK (duration_minutes >= 0)
);

-- Create index for faster searches
CREATE INDEX idx_labtests_name ON lab_tests(test_name);
CREATE INDEX idx_labtests_dept ON lab_tests(department);

-- ============================================
-- HOSPITAL BEDS TABLE
-- ============================================
CREATE TABLE hospital_beds (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bed_number VARCHAR2(50) UNIQUE NOT NULL,
    ward_name VARCHAR2(100) NOT NULL,
    bed_type VARCHAR2(50) NOT NULL,
    price_per_day NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'available',
    floor_number NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_bed_status CHECK (status IN ('available', 'occupied', 'maintenance')),
    CONSTRAINT chk_bed_price CHECK (price_per_day >= 0)
);

-- Create index for faster searches
CREATE INDEX idx_beds_ward ON hospital_beds(ward_name);
CREATE INDEX idx_beds_status ON hospital_beds(status);
CREATE INDEX idx_beds_type ON hospital_beds(bed_type);

-- ============================================
-- INSERT SAMPLE DATA
-- ============================================

-- Sample Medicines
INSERT INTO medicines (name, description, manufacturer, price, stock_quantity, expiry_date, category)
VALUES ('Paracetamol 500mg', 'Pain reliever and fever reducer', 'PharmaCorp', 5.99, 500, TO_DATE('2025-12-31', 'YYYY-MM-DD'), 'Painkiller');

INSERT INTO medicines (name, description, manufacturer, price, stock_quantity, expiry_date, category)
VALUES ('Amoxicillin 250mg', 'Antibiotic for bacterial infections', 'MediLife', 12.50, 200, TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'Antibiotic');

INSERT INTO medicines (name, description, manufacturer, price, stock_quantity, expiry_date, category)
VALUES ('Ibuprofen 400mg', 'Anti-inflammatory pain reliever', 'HealthPlus', 8.75, 350, TO_DATE('2025-09-15', 'YYYY-MM-DD'), 'Painkiller');

INSERT INTO medicines (name, description, manufacturer, price, stock_quantity, expiry_date, category)
VALUES ('Omeprazole 20mg', 'Reduces stomach acid production', 'GastroMed', 15.00, 180, TO_DATE('2025-11-20', 'YYYY-MM-DD'), 'Antacid');

-- Sample Lab Tests
INSERT INTO lab_tests (test_name, description, price, department, preparation_required, duration_minutes)
VALUES ('Complete Blood Count (CBC)', 'Measures different components of blood', 25.00, 'Pathology', 'Fasting for 8-12 hours', 30);

INSERT INTO lab_tests (test_name, description, price, department, preparation_required, duration_minutes)
VALUES ('X-Ray Chest', 'Imaging test for chest and lungs', 45.00, 'Radiology', 'Remove metal objects', 15);

INSERT INTO lab_tests (test_name, description, price, department, preparation_required, duration_minutes)
VALUES ('Lipid Profile', 'Cholesterol and triglycerides test', 30.00, 'Pathology', 'Fasting for 12 hours', 20);

INSERT INTO lab_tests (test_name, description, price, department, preparation_required, duration_minutes)
VALUES ('Blood Sugar (Fasting)', 'Measures glucose levels in blood', 15.00, 'Pathology', 'Fasting for 8 hours', 10);

INSERT INTO lab_tests (test_name, description, price, department, preparation_required, duration_minutes)
VALUES ('Ultrasound Abdomen', 'Imaging of abdominal organs', 60.00, 'Radiology', 'Empty bladder before test', 30);

-- Sample Beds
INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('ICU-101', 'ICU', 'ICU', 500.00, 'available', 3);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('ICU-102', 'ICU', 'ICU', 500.00, 'occupied', 3);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('GW-201', 'General Ward', 'General', 100.00, 'available', 2);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('GW-202', 'General Ward', 'General', 100.00, 'available', 2);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('GW-203', 'General Ward', 'General', 100.00, 'occupied', 2);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('PVT-301', 'Private Room', 'Private', 300.00, 'available', 3);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('PVT-302', 'Private Room', 'Private', 300.00, 'available', 3);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('DLX-401', 'Deluxe Suite', 'Deluxe', 800.00, 'available', 4);

INSERT INTO hospital_beds (bed_number, ward_name, bed_type, price_per_day, status, floor_number)
VALUES ('GW-110', 'General Ward', 'General', 100.00, 'maintenance', 1);

COMMIT;

-- ============================================
-- VERIFY DATA
-- ============================================
SELECT 'Medicines Count: ' || COUNT(*) as info FROM medicines;
SELECT 'Lab Tests Count: ' || COUNT(*) as info FROM lab_tests;
SELECT 'Beds Count: ' || COUNT(*) as info FROM hospital_beds;

-- Show sample data
SELECT * FROM medicines;
SELECT * FROM lab_tests;
SELECT * FROM hospital_beds;
