CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    pass VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    role VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Medicines table
CREATE TABLE medicines (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    description VARCHAR2(500),
    manufacturer VARCHAR2(200),
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    expiry_date DATE,
    category VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Lab tests table
CREATE TABLE lab_tests (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    test_name VARCHAR2(200) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10,2) NOT NULL,
    department VARCHAR2(100),
    preparation_required VARCHAR2(500),
    duration_minutes NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Beds table
CREATE TABLE beds (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bed_number VARCHAR2(50) UNIQUE NOT NULL,
    ward_name VARCHAR2(100) NOT NULL,
    bed_type VARCHAR2(50) NOT NULL,
    price_per_day NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'available',
    floor_number NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_bed_status CHECK (status IN ('available', 'occupied', 'maintenance'))
);